class CourseData:

    def __init__(self, filename):

        import json
        from pprint import pprint

        with open(filename, encoding="utf8") as f:
            self.data = json.load(f)["items"] 
            # data is a dictionary of dictionaries, each corresponding to a course

    def get_course_count(self):
        """Returns: int, total number of courses"""

        course_count = 0
        for entry in data:
            if entry["type"] == "Class":
                course_count += 1
        return course_count

    def get_full_dict(self):
        """Returns: dictionary, copy of full dictionary generated by json file"""

        return self.data.copy()

    def get_attribute(self, entry, attribute="id"):
        """Gets the attribute of an entry. Possible attributes listed below.
        'type': 'Class', 'RecitationSession', 'LectureSession', 'LabSession'
        'id': course code
        'label': course title
        'level':
        'description'
        'prereqs'
        'equivalent_subjects'
        'joint_subjects'
        'hass_attribute'
        'gir_attribute'
        'total-units'
        'course'

        input: string, name of attribute
        returns: string, value of attribute
        """
        return entry[attribute]

    def print_courses(self):
        """Prints list of courses, as well as their descriptions, procedurally.
        Returns: None"""

        import time

        course_count = 0
        for entry in self.data:
            if entry["type"] == "Class":
                print(entry["id"] + ": " + entry["label"])
                time.sleep(0.01)

        print("Length: " + str(self.get_course_count()))
        
dat = CourseData("course_data.json")
dat.print_courses()



